/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:45fe023b-cb2b-4349-998e-89c87881b869",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_f3onOurMk",
    "aws_user_pools_web_client_id": "3h55fjnrbrqsn1edu6knts97vm",
    "oauth": {}
};


export default awsmobile;
