/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:aac8d7d2-65f5-433d-99e8-3e511e7cfd7b",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_62hQ2kdrD",
    "aws_user_pools_web_client_id": "3oj2u8i2fsq8qmslls363k8va",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bxcndlcxcvcfzdsuzxk3tc6qwy.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
a
